### PR TITLE
Add sample historical footprints

### PR DESCRIPTION
**Pull request by mdsimpson42**
Can now toggle between:
- Historical Map (No Footprints)
- Historical Map with Modern Footprints
- Historical Map with Historial Footprints (Sample)

Deploying to Staging for AI UK.

### CODE REVIEW

**Comment by matkoniecz** [comment]
I think we should revert it from colouring core and restore earlier version and either apply changes to Colouring Britain or pick up changes relevant in general without bring UK-only parts to Colouring Core.

**Comment by mdsimpson42** [comment]
Yes, I know. I only realised afterwards... I have no idea why it seemed to default to core:master instead of Britain:master. I tried to revert it, but I don't think I got it all? I'm so confused!

**Comment by matkoniecz** [comment]
f5abdfed is the last commit before this merge and we have no later valuable commits on this branch, hopefully noone else updated their repo

**Comment by mdsimpson42** [comment]
Ok, still confused. Do I run these commands in London or Core?

> I would do
> 
> ```
> git checkout master
> git reset --hard f5abdfed
> git push --force upstream
> ```

Also ```git push --force``` doesn't work - it asks me to log in and then says ```Support for password authentication was removed on August 13, 2021.```

**Comment by mdsimpson42** [comment]
I'd thought I'd found a way around the authentication, but now its saying the branch is protected and it won't let me do it!

**Comment by matkoniecz** [comment]
>  Do I run these commands in London or Core?

For core repository - to get rid of this commits even in history

> but now its saying the branch is protected and it won't let me do it!

So either you can change setting to unprotect (its whole point is to block `--force` pushes) temporarily or I can make megacommit reverting all this changes and open PR.

**Comment by mdsimpson42** [comment]
OK, I think I've got it now. Sorry for the confusion and thanks for the help!

**Comment by polly64** [comment]
See you later


Polly Hudson
Senior Research Fellow, The Alan Turing Institute
Project Lead:  Colouring Cities Research Programme
 https://www.turing.ac.uk/research/research-projects/colouring-cities-research-programme

The Alan Turing Institute is the UK's national institute for data science and artificial Intelligence.
The Alan Turing Institute is a limited liability company, registered in England with registered number 09512457 with registered offices at British Library, 96 Euston Road, London, England, NW1 2DB. We are also a charity registered in England with charity number 1162533. DISCLAIMER: Although we have taken reasonable precautions to ensure the completeness and accuracy of this e-mail, transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or be incomplete. If you receive a suspicious or unexpected email from us, or purporting to have been sent on our behalf, particularly containing different bank details, please do not reply to the email, click on any links, open any attachments, or comply with any instructions contained within it. Our Transparency Notice found here - https://www.turing.ac.uk/transparency-notice sets out how and why we collect, store, use and share your personal data and it explains your rights and how to raise concerns with us.

On 14/03/2024, 15:38, "Mike Simpson" ***@***.***> wrote:


OK, I think I've got it now. Sorry for the confusion and thanks for the help!

**Pull request merged**
